queue_rules:
  - name: default
    merge_method: rebase
    conditions:
      # Conditions to get out of the queue (= merged)
      - status-success=Tests (lint)
      - status-success=Tests (format)
      - status-success=Tests (licenses)
      - status-success=Tests (security)
      - status-success=Tests (docs)
      - status-success=Tests (py38)
      - status-success=Tests (py39)
      - status-success=Tests (py310)
      - status-success=Tests (py311)
      - status-success=Tests (py312)


pull_request_rules:

  - name: Merge on approval
    actions:
      queue:
        name: default
    conditions:
      - label!=WIP
      - -draft
      - approved-reviews-by=@fedora-infra/authdev
      - "#changes-requested-reviews-by=0"
      - status-success=DCO
      - status-success=Tests (lint)
      - status-success=Tests (format)
      - status-success=Tests (licenses)
      - status-success=Tests (security)
      - status-success=Tests (docs)
      - status-success=Tests (py38)
      - status-success=Tests (py39)
      - status-success=Tests (py310)
      - status-success=Tests (py311)
      - status-success=Tests (py312)

